/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package friendbot;

import java.util.Random;

/**
 *
 * @author Nugraha
 */
public class BotUI extends javax.swing.JFrame {

    /**
     * Creates new form BotUI
     */
    public BotUI() {
        initComponents();
        
        setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TA1 = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        TA2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(122, 71, 221), 2), " Chat Bot ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Kristen ITC", 1, 28), new java.awt.Color(122, 71, 221))); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setBorder(null);
        jScrollPane1.setToolTipText("");

        TA1.setEditable(false);
        TA1.setColumns(20);
        TA1.setFont(new java.awt.Font("Kristen ITC", 1, 17)); // NOI18N
        TA1.setForeground(new java.awt.Color(122, 71, 221));
        TA1.setRows(5);
        TA1.setBorder(null);
        jScrollPane1.setViewportView(TA1);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 51, 580, 220));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 610, 290));

        jLabel2.setFont(new java.awt.Font("Jokerman", 1, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(122, 71, 221));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("X");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 0, 70, 50));

        TA2.setFont(new java.awt.Font("Kristen ITC", 1, 18)); // NOI18N
        TA2.setForeground(new java.awt.Color(122, 71, 221));
        TA2.setText("Enter the message");
        TA2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(122, 71, 221)));
        TA2.setCaretColor(new java.awt.Color(122, 71, 221));
        TA2.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        TA2.setDisabledTextColor(new java.awt.Color(122, 71, 221));
        TA2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TA2MouseClicked(evt);
            }
        });
        TA2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TA2ActionPerformed(evt);
            }
        });
        jPanel1.add(TA2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 430, 70));
        TA2.getAccessibleContext().setAccessibleName("");

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Kristen ITC", 3, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(122, 71, 221));
        jButton1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.black, null, null));
        jButton1.setLabel("Send");
        jButton1.setName(""); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jButton1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton1KeyPressed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 350, 150, 70));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 440));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabel2MouseClicked

    private void TA2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TA2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TA2ActionPerformed

    private void TA2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TA2MouseClicked
        TA2.setText("");
    }//GEN-LAST:event_TA2MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String query=TA2.getText();
		TA1.append(" You: "+query+"\n");
		//query.trim();
		query=query.toLowerCase();
		if(query.contains("clear screen")||query.contains("clr")||query.contains("cls"))
		{
			TA1.setText("");
			TA2.setText("");
		}
		else if(query.contains("hi")||query.contains("hey")||query.contains("hola")||query.contains("hello") ||query.contains("hai") ||query.contains("hii"))
		{
			Random rand=new Random();
			int a=rand.nextInt(3);
			if(a==0)
			{
				ai("Hi....");
			}
			else if(a==1)
			{
				ai("Hello....");
			}
                        else if(a==2)
			{
				ai("Hey....");
			}
			
			
		}
		else if((query.contains("your name?")||query.contains("you name")||query.contains("who are you")) && !query.contains("my name"))
		{
			Random rand=new Random();
			int a=rand.nextInt(1);
			if(a==0)
			{
				ai("My Name is AI... And you?");
			}
			else if(a==1)
			{
				ai("My Name is AI... How about you?");
			}
		}
                
                else if(query.contains("my name is") && !(query.contains("your name?")||query.contains("you name")||query.contains("who are you")))
		{
			Random rand=new Random();
			int a=rand.nextInt(1);
			if(a==0)
			{
				ai("It's a beautiful name");
                                
			}
			else if(a==1)
			{
				ai("That's a great name");
                               
			}
		}
                
                else if((query.contains("your name?")||query.contains("you name")||query.contains("who are you")) && query.contains("my name"))
		{
			Random rand=new Random();
			int a=rand.nextInt(1);
			if(a==0)
			{
				ai("My Name is AI... What are you doing?");
			}
			else if(a==1)
			{
				ai("My Name is AI... What do you think about me?");
			}
		}
                
                else if(query.contains("thank you"))
		{
			Random rand=new Random();
			int a=rand.nextInt(1);
			if(a==0)
			{
                            ai("BTW... Thank you so much for talking the time to talk with me. Sorry, I have to go now :(   ");
			}
			else if(a==1)
			{
                            ai("Oh, look at the time! I think I have to go now... Sorry :( ");   
			}
		}
                else if(query.contains("start")){
                       TA1.setText("PROVIDE THE STATE BY ENTERING A DIGIT\n1.Andhra Pradesh\n2.Arunachal Pradesh\n3.Assam\n4.Bihar\n5.Chhattisgarh\n6.Goa\n7.Gujarat\n8.Tamil Nadu\n8.West Bengal");
                       if((query.contains("1")||query.contains("2")||query.contains("3")) || query.contains("4")|| query.contains("5")|| query.contains("6")|| query.contains("7")|| query.contains("8"))
		       {
			Random rand=new Random();
			int a=rand.nextInt(1);
			if(a==0)
			{
				ai("Provide the District to proceed further by selecting a digit\n1.Srikakulam\n2.Parvathipuramu Manyam \n3.Vizianagaram\n4.Visakhapatnam\n5.Alluri Sitharama Raju\n6.Anakapalli\n7.Kakinada");
			}
			else if(a==1)
			{
				ai("My Name is AI... What do you think about me?");
			}
                        else if(a==2)
			{
				ai("My Name is AI... What do you think about me?");
			}else if(a==3)
			{
				ai("My Name is AI... What do you think about me?");
			}else if(a==4)
			{
				ai("My Name is AI... What do you think about me?");
			}else if(a==5)
			{
				ai("My Name is AI... What do you think about me?");
			}else if(a==6)
			{
				ai("My Name is AI... What do you think about me?");
			}else if(a==7)
			{
				ai("My Name is AI... What do you think about me?");
			}
                        }
                       else{
                           Random rand=new Random();
			int a=rand.nextInt(4);
			if(a==0)
			{
				ai("Sorry,I'cant get you");
			}
			else if(a==1)
			{
				ai("Plase say it correctly");
			}
			else if(a==2)
			{
				ai("Please rephrase that");
			}
			else if(a==3)
			{
				ai("???");
			}
                       }
                }
                
		else{
			Random rand=new Random();
			int a=rand.nextInt(4);
			if(a==0)
			{
				ai("Sorry,I'cant get you");
			}
			else if(a==1)
			{
				ai("Plase say it correctly");
			}
			else if(a==2)
			{
				ai("Please rephrase that");
			}
			else if(a==3)
			{
				ai("???");
			}
		}
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton1KeyPressed
        // TODO add your handling code here:
        String query=TA2.getText();
		TA1.append(" You: "+query+"\n");
		//query.trim();
		query=query.toLowerCase();
		if(query.contains("clear screen")||query.contains("clr")||query.contains("cls"))
		{
			TA1.setText("");
			TA2.setText("");
		}
		else if(query.contains("hi")||query.contains("hey")||query.contains("hola")||query.contains("hello") ||query.contains("hai") ||query.contains("hii"))
		{
			Random rand=new Random();
			int a=rand.nextInt(3);
			if(a==0)
			{
				ai("Hi....");
			}
			else if(a==1)
			{
				ai("Hello....");
			}
                        else if(a==2)
			{
				ai("Hey....");
			}
			
			
		}
		else if((query.contains("your name?")||query.contains("you name")||query.contains("who are you")) && !query.contains("my name"))
		{
			Random rand=new Random();
			int a=rand.nextInt(1);
			if(a==0)
			{
				ai("My Name is AI... And you?");
			}
			else if(a==1)
			{
				ai("My Name is AI... How about you?");
			}
		}
                
                else if(query.contains("my name is") && !(query.contains("your name?")||query.contains("you name")||query.contains("who are you")))
		{
			Random rand=new Random();
			int a=rand.nextInt(1);
			if(a==0)
			{
				ai("It's a beautiful name");
                                
			}
			else if(a==1)
			{
				ai("That's a great name");
                               
			}
		}
                
                else if((query.contains("your name?")||query.contains("you name")||query.contains("who are you")) && query.contains("my name"))
		{
			Random rand=new Random();
			int a=rand.nextInt(1);
			if(a==0)
			{
				ai("My Name is AI... What are you doing?");
			}
			else if(a==1)
			{
				ai("My Name is AI... What do you think about me?");
			}
		}
                
                else if(query.contains("thank you"))
		{
			Random rand=new Random();
			int a=rand.nextInt(1);
			if(a==0)
			{
                            ai("BTW... Thank you so much for talking the time to talk with me. Sorry, I have to go now :(   ");
			}
			else if(a==1)
			{
                            ai("Oh, look at the time! I think I have to go now... Sorry :( ");   
			}
		}
                else if(query.contains("start")){
                       TA1.setText("PROVIDE THE STATE BY ENTERING A DIGIT\n1.Andhra Pradesh\n2.Arunachal Pradesh\n3.Assam\n4.Bihar\n5.Chhattisgarh\n6.Goa\n7.Gujarat\n8.Tamil Nadu\n8.West Bengal");
                       if((query.contains("1")||query.contains("2")||query.contains("3")) || query.contains("4")|| query.contains("5")|| query.contains("6")|| query.contains("7")|| query.contains("8"))
		       {
			Random rand=new Random();
			int a=rand.nextInt(1);
			if(a==0)
			{
				ai("Provide the District to proceed further by selecting a digit\n1.Srikakulam\n2.Parvathipuramu Manyam \n3.Vizianagaram\n4.Visakhapatnam\n5.Alluri Sitharama Raju\n6.Anakapalli\n7.Kakinada");
			}
			else if(a==1)
			{
				ai("My Name is AI... What do you think about me?");
			}
                        else if(a==2)
			{
				ai("My Name is AI... What do you think about me?");
			}else if(a==3)
			{
				ai("My Name is AI... What do you think about me?");
			}else if(a==4)
			{
				ai("My Name is AI... What do you think about me?");
			}else if(a==5)
			{
				ai("My Name is AI... What do you think about me?");
			}else if(a==6)
			{
				ai("My Name is AI... What do you think about me?");
			}else if(a==7)
			{
				ai("My Name is AI... What do you think about me?");
			}
                        }
                       else{
                           Random rand=new Random();
			int a=rand.nextInt(4);
			if(a==0)
			{
				ai("Sorry,I'cant get you");
			}
			else if(a==1)
			{
				ai("Plase say it correctly");
			}
			else if(a==2)
			{
				ai("Please rephrase that");
			}
			else if(a==3)
			{
				ai("???");
			}
                       }
                }
                
		else{
			Random rand=new Random();
			int a=rand.nextInt(4);
			if(a==0)
			{
				ai("Sorry,I'cant get you");
			}
			else if(a==1)
			{
				ai("Plase say it correctly");
			}
			else if(a==2)
			{
				ai("Please rephrase that");
			}
			else if(a==3)
			{
				ai("???");
			}
		}
    }//GEN-LAST:event_jButton1KeyPressed

void ai(String s)
	{
		TA1.append(" Bot : "+s+"\n\n");
		TA2.setText("");
	}

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BotUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BotUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BotUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BotUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BotUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea TA1;
    private javax.swing.JTextField TA2;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
